version: "3.9"

services:
  api:
    build:
      context: .
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - app-net


  php:
    image: php:8.2-apache
    container_name: php_frontend
    volumes:
      - ./App:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - app-net


  postgres:
      image: postgres:latest
      restart: always
      ports:
          - "5432:5432"
      environment:
          POSTGRES_USER: ${PG_USER}
          POSTGRES_PASSWORD: ${PG_PASS}
          POSTGRES_DB: ${PG_DB}
      volumes:
          - ./pgdata:/var/lib/postgresql/data
      networks:
        - app-net

  pgadmin:
      image: dpage/pgadmin4:latest
      environment:
          PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
          PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      ports:
          - "5050:80"
      depends_on:
          - postgres
      networks:
        - app-net

volumes:
  postgres_data:

networks:
  app-net:
